please don't be ugly
ropensci/lingtypology pull request #66
Opened 2021-06-05 07:50 UTC by kirillkoncha

2021-10-12 17:46 UTC, agricolamz commented
@kirillkoncha, please, rename pull request, describe, changes

2021-10-25 08:42 UTC, kirillkoncha commented
> @kirillkoncha, please, rename pull request, describe, changes

изменил, посмотрите изменения пожалуйста

2021-10-25 09:22 UTC, agricolamz commented on tests/testthat/test-wcs-feature.R
> +context("Tests for eurasianphonology.feature function")
wrong context, just remove this line

2021-10-25 09:24 UTC, agricolamz requested changes
work more on documentation

2021-10-25 09:24 UTC, agricolamz commented on R/wcs_bk.R
> +#'   \item{language}{Another Language name}
can you add more meaningful comments?

2021-10-25 09:24 UTC, agricolamz commented on R/wcs.feature.R
> +http://www.icsi.berkeley.edu/wcs/data.html")
can you add a proper citations?

2021-11-18 13:46 UTC, closed without merging