WCS updated
ropensci/lingtypology pull request #73
Opened 2021-11-16 14:14 UTC by kirillkoncha

2021-11-18 14:08 UTC, agricolamz requested changes

2021-11-18 14:08 UTC, agricolamz commented on R/wcs.feature.R
> +    {result <- lingtypology::wcs_bk
фигурная скобка на предыдущей строке

2021-11-18 14:08 UTC, agricolamz commented on R/wcs.feature.R
> +    message("Function doesn't have this parameter")
можно поосмысленней комментарий? Что мешает перечислить все возможные параметры?

2021-11-18 14:08 UTC, agricolamz commented on R/wcs.R
> +#'   \item{language}{Language name lingtypology}
поправьте английский

2021-11-18 14:08 UTC, agricolamz commented on R/wcs_bk.R
> +"wcs_bk"
поменяйте `Huastec, San Luís Potosí` на `Huastec`

2021-11-18 14:08 UTC, agricolamz commented on R/wcs.feature.R
> +#' @param feature Berlin and Kay for Database of Berlin and Kay; WCS for World Color Survey Database
напишите в кавычках, чтобы было понятно, что нужно набирать

2021-11-18 14:08 UTC, agricolamz commented on R/wcs.feature.R
> +#' @param feature Berlin and Kay for Database of Berlin and Kay; WCS for World Color Survey Database
ну и вообще, лучше пояснее написать, что это за две базы данных

2021-11-18 14:08 UTC, agricolamz commented on R/wcs.feature.R
> +  if (feature == "WCS") {
лол, это не работает. нужно `else if`. Сейчас функция не работает, если вызвать "Berlin and Kay"

2021-11-18 14:08 UTC, agricolamz commented on database_creation/wcs_database_creation.R
> +colors <- utils::read.csv("/Users/kirillkonca/lingtypology/database_creation/colors.csv",
абсолютный путь, это никогда не заработает на моем компьютере

2021-11-18 14:08 UTC, agricolamz commented on database_creation/wcs_database_creation.R
> +codes <- read.csv("/Users/kirillkonca/lingtypology/database_creation/wcs_codes.csv", sep = ";")
абсолютный путь, это никогда не заработает на моем компьютере

2021-11-18 14:08 UTC, agricolamz commented on database_creation/wcs_database_creation.R
> +save(wcs, file="/Users/kirillkonca/lingtypology/data/wcs.RData", compress= 'xz')
абсолютный путь, это никогда не заработает на моем компьютере

2021-11-18 14:08 UTC, agricolamz commented on database_creation/wcs_database_creation.R
> +save(wcs_bk, file="/Users/kirillkonca/lingtypology/data/wcs_bk.RData", compress= 'xz')
абсолютный путь, это никогда не заработает на моем компьютере

2021-11-18 14:08 UTC, agricolamz commented on tests/testthat/test-wcs-feature.R
> +  expect_length(wcs.feature("WCS"), 19)})
Добавьте тест и на другой вариант аргумента

2021-12-06 19:56 UTC, kirillkoncha commented on R/wcs.feature.R
> +  if (feature == "WCS") {
да вроде работает у меня по крайней мере

2021-12-07 08:47 UTC, closed without merging